[project]
name = "speech-recognize-providers"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.116.1",
    "httpx>=0.28.1",
    "mcp[cli]>=1.12.0",
    "parakeet-mlx>=0.3.5",
    "uvicorn>=0.35.0",
]
